default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: db/development

test:
  <<: *default
  database: db/test

production:
  <<: *default
  database: db/production
